export type Tag = "veg" | "nonveg" | "both";

export type MenuItem = {
  name: string;
  desc?: string;
  price: string; // numeric strings get a "₹" prefix in the UI; labelled strings render as-is
  icon: string; // filename (without extension) in /public/menu-icons
  tag?: Tag; // overrides the category defaultTag
};

export type MenuCategory = {
  id: string;
  title: string;
  note?: string;
  defaultTag?: Tag;
  items: MenuItem[];
};

export const menu: MenuCategory[] = [
  {
    id: "breakfast",
    title: "Breakfast",
    note: "Available 7:30 AM – 10:30 AM",
    defaultTag: "veg",
    items: [
      { name: "Freshly Squeezed Fruit Juice", price: "180", icon: "juice" },
      { name: "Seasonal Cut Fruit Platter", price: "250", icon: "fruit" },
      {
        name: "Choice of Eggs",
        desc: "Boiled, poached or scrambled",
        price: "80 / 120",
        icon: "egg",
        tag: "nonveg",
      },
      {
        name: "Choice of Omelettes with Toast",
        desc: "Plain / masala omelette, cheese, mushroom",
        price: "120 / 150 / 200",
        icon: "omelette",
        tag: "nonveg",
      },
      {
        name: "English Breakfast",
        desc: "Toasted bread, egg to order, baked beans, hash brown potato, sautéed mushroom, juice, tea or coffee",
        price: "550",
        icon: "breakfast-plate",
        tag: "nonveg",
      },
      {
        name: "Continental Breakfast",
        desc: "Choice of juice, tea & coffee, pancake (honey / nutella), butter toast, jam or marmalade, cereals",
        price: "450",
        icon: "croissant",
      },
      {
        name: "Indian Breakfast",
        desc: "Choice of paratha (2 pcs) served with butter, pickle / curd, tea, coffee",
        price: "450",
        icon: "paratha",
      },
      {
        name: "Poori Bhaji (2 pcs)",
        desc: "Mildly spiced potato curry served with golden fried puffed poori and pickle",
        price: "250",
        icon: "poori",
      },
      { name: "Chana Bhatura (3 pcs)", price: "250", icon: "poori" },
      {
        name: "Pancake & Waffles",
        desc: "Served with maple syrup or honey and melted butter",
        price: "250",
        icon: "pancake",
      },
      {
        name: "Choice of Cereals",
        desc: "Cornflakes, chocoflakes or muesli served with hot or cold milk",
        price: "250",
        icon: "cereal",
      },
      {
        name: "Choice of Paratha",
        desc: "Indian bread with choice of stuffing served with pickle",
        price: "180",
        icon: "paratha",
      },
    ],
  },
  {
    id: "cafe",
    title: "Café",
    note: "Taxes as applicable",
    defaultTag: "veg",
    items: [
      { name: "Cappuccino", price: "165", icon: "coffee" },
      { name: "Espresso", price: "140", icon: "coffee" },
      { name: "Latte", price: "165", icon: "coffee" },
    ],
  },
  {
    id: "hot-beverages",
    title: "Hot Beverages",
    defaultTag: "veg",
    items: [
      { name: "Black Tea", price: "70", icon: "tea" },
      { name: "Milk Tea", price: "99", icon: "tea" },
      { name: "Green Tea", price: "90", icon: "tea" },
      { name: "Ginger Lemon Honey", price: "150", icon: "tea" },
      { name: "Hot Milk", price: "120", icon: "milk" },
      { name: "Hot Chocolate", price: "200", icon: "hot-chocolate" },
    ],
  },
  {
    id: "cold-beverages",
    title: "Cold Beverages",
    defaultTag: "veg",
    items: [
      { name: "Classic Cold Coffee", price: "200", icon: "cold-coffee" },
      { name: "Oreo Milkshake", price: "220", icon: "milkshake" },
      { name: "Kit-Kat Milkshake", price: "220", icon: "milkshake" },
      { name: "Vanilla Milkshake", price: "220", icon: "milkshake" },
      { name: "Strawberry Milkshake", price: "220", icon: "milkshake" },
      { name: "Banana / Mango Milkshake", price: "220", icon: "milkshake" },
      { name: "Fresh Lime Water", price: "100", icon: "lime-soda" },
      { name: "Fresh Lime Soda", price: "150", icon: "lime-soda" },
      { name: "Packaged Water Bottle", price: "50", icon: "water-bottle" },
      { name: "Aerated Drinks", price: "150", icon: "soft-drink" },
      { name: "Lassi (Sweet & Salted)", price: "140", icon: "lassi" },
      { name: "Iced Tea", price: "120", icon: "iced-tea" },
    ],
  },
  {
    id: "salad",
    title: "Salad",
    defaultTag: "veg",
    items: [
      {
        name: "Garden Fresh Green Salad",
        desc: "A mix of garden fresh vegetables",
        price: "150",
        icon: "salad",
      },
      {
        name: "Classic Caesar Salad",
        desc: "Green lettuce with a classical dressing of mustard and mayonnaise",
        price: "220",
        icon: "salad",
      },
      {
        name: "Waldorf Salad",
        desc: "A combo of fruits and walnut with creamy dressing",
        price: "230",
        icon: "salad",
      },
      {
        name: "Russian Salad",
        desc: "Vegetables dressed with creamy mayonnaise",
        price: "220",
        icon: "salad",
      },
      {
        name: "Greek Salad",
        desc: "Traditional Mediterranean dish with tomato, cucumber, red onion, green bell peppers and olives",
        price: "250",
        icon: "salad",
      },
    ],
  },
  {
    id: "soups-shorba",
    title: "Soups & Shorba",
    note: "12:30 PM – 3:30 PM & 7:00 PM – 10:30 PM",
    defaultTag: "veg",
    items: [
      {
        name: "Lemon Coriander",
        desc: "Clear oriental soup served with vegetables",
        price: "190",
        icon: "soup",
      },
      {
        name: "Hot & Sour",
        desc: "A thick Chinese specialty with strips of healthy vegetables",
        price: "Veg ₹190 · Non-veg ₹230",
        icon: "soup",
        tag: "both",
      },
      {
        name: "Sweet Corn",
        desc: "The popular mild Chinese delicacy",
        price: "Veg ₹190 · Non-veg ₹230",
        icon: "soup",
        tag: "both",
      },
      {
        name: "Manchow Soup",
        desc: "Spiced broth of vegetable / chicken with crispy noodles",
        price: "Veg ₹170 · Non-veg ₹230",
        icon: "soup",
        tag: "both",
      },
      {
        name: "Tomato Dhaniya Ka Shorba",
        desc: "Aromatic thin tomato stock flavoured with green coriander",
        price: "190",
        icon: "soup",
      },
      {
        name: "Choice of Cream Soup",
        desc: "Tomato, mushroom, vegetable or chicken",
        price: "Veg ₹200 · Non-veg ₹250",
        icon: "soup",
        tag: "both",
      },
    ],
  },
  {
    id: "veg-starters",
    title: "Veg Starters & Appetizers",
    defaultTag: "veg",
    items: [
      {
        name: "Dahi Ke Kabab",
        desc: "Vegetarian patties made with hung curd, paneer and aromatic spices",
        price: "400",
        icon: "tikki",
      },
      {
        name: "Dahi Ke Sholay",
        desc: "Creamy, mildly spiced hung curd and vegetable filling enveloped in a thin slice of bread",
        price: "350",
        icon: "bread-roll",
      },
      {
        name: "Veg Gulabi Kabab",
        desc: "Beetroot and mixed vegetable patties infused with aromatic spices",
        price: "350",
        icon: "tikki",
      },
      {
        name: "Veg Seekh Kabab",
        desc: "Spiced vegetable and paneer skewers, tandoor grilled till golden",
        price: "360",
        icon: "seekh-kabab",
      },
      {
        name: "Mushroom Duplex",
        desc: "Twin mushroom caps packed with a gooey cheesy and herb filling, golden fried",
        price: "480",
        icon: "mushroom",
      },
      {
        name: "Veg Nuggets",
        desc: "Bite-sized vegetarian snacks, crispy outside and soft inside",
        price: "320",
        icon: "nuggets",
      },
      {
        name: "Choice of Paneer Tikka",
        desc: "Achari, malai, haryali or peshawari",
        price: "400",
        icon: "tikka-skewer",
      },
    ],
  },
  {
    id: "nonveg-starters",
    title: "Non-Veg Starters & Appetizers",
    defaultTag: "nonveg",
    items: [
      {
        name: "Mutton Seekh Kabab",
        desc: "Finely minced lamb / goat meat blended with aromatic spices and herbs",
        price: "500",
        icon: "seekh-kabab",
      },
      {
        name: "Chicken Nuggets",
        desc: "Bite-sized boneless chicken, lightly seasoned and fried golden",
        price: "400",
        icon: "nuggets",
      },
      {
        name: "Choice of Chicken Tikka",
        desc: "Achari, malai, haryali or peshawari",
        price: "470",
        icon: "tikka-skewer",
      },
      {
        name: "Chicken Seekh Kabab",
        desc: "Diced chicken skewers, tandoor grilled till golden",
        price: "450",
        icon: "seekh-kabab",
      },
      {
        name: "Afghani Murg",
        desc: "Creamy cheese, yogurt and spice blended chicken tikka roasted in charcoal tandoor",
        price: "Half ₹400 · Full ₹600",
        icon: "tandoori-leg",
      },
      {
        name: "Lahori Murg Tikka",
        desc: "Red chili powder, yogurt and spice marinated chicken roasted in charcoal tandoor",
        price: "Half ₹400 · Full ₹650",
        icon: "tandoori-leg",
      },
      {
        name: "Chicken ’65’",
        desc: "Spicy deep-fried South Indian chicken tossed with curry leaves, red chillies and tangy spices",
        price: "Half ₹380 · Full ₹650",
        icon: "fried-chicken",
      },
      {
        name: "Chilli Chicken",
        desc: "Crispy batter-fried chicken tossed in a glossy soy, chilli garlic and bell pepper sauce",
        price: "Half ₹390 · Full ₹660",
        icon: "chilli",
      },
    ],
  },
  {
    id: "fish",
    title: "Fish",
    defaultTag: "nonveg",
    items: [
      {
        name: "Tandoori Trout",
        desc: "Marinated with Indian spices and cooked in a charcoal oven",
        price: "850",
        icon: "fish",
      },
      {
        name: "Fish Tikka",
        desc: "Smoky tandoori tikka marinated in yogurt, ginger, garlic, spices & lemon",
        price: "650",
        icon: "fish",
      },
      { name: "Chilli Fish", price: "540", icon: "fish" },
      { name: "Fish Finger", price: "540", icon: "fish" },
      { name: "Haryali Mahi Tikka", price: "540", icon: "fish" },
      {
        name: "Fish Amritsari",
        desc: "Fenugreek flavoured fish chunks, deep fried and served with mint sauce",
        price: "560",
        icon: "fish",
      },
    ],
  },
  {
    id: "mutton",
    title: "Choice of Mutton",
    defaultTag: "nonveg",
    items: [
      {
        name: "Mutton Rogan Josh",
        desc: "Tender bone-in mutton slow-cooked in a rich, velvety gravy",
        price: "700",
        icon: "curry",
      },
      {
        name: "Mutton Curry",
        desc: "Tender goat / lamb simmered in a robust spiced gravy",
        price: "700",
        icon: "curry",
      },
      {
        name: "Mutton Masala",
        desc: "Tender mutton simmered in a spiced onion, tomato and yogurt gravy",
        price: "700",
        icon: "curry",
      },
      {
        name: "Mutton Saagwala",
        desc: "Slow-cooked mutton in a vibrant, velvety spinach and herb gravy",
        price: "700",
        icon: "curry",
      },
    ],
  },
  {
    id: "veg-delight",
    title: "Vegetarian Delight",
    defaultTag: "veg",
    items: [
      {
        name: "Chilli Paneer (Dry)",
        desc: "Cottage cheese, fresh chillies and assorted bell pepper",
        price: "350",
        icon: "paneer",
      },
      {
        name: "Paneer 65",
        desc: "Cottage cheese in the classic ’65’ style",
        price: "350",
        icon: "paneer",
      },
      {
        name: "Chilli Garlic Mushroom",
        desc: "Crispy fried mushroom tossed in sweet and spicy chilli sauce",
        price: "320",
        icon: "mushroom",
      },
      { name: "Corn Salt and Pepper", price: "300", icon: "corn" },
      {
        name: "Veg Manchurian (Dry)",
        desc: "Indo-Chinese fusion of mushroom and baby corn",
        price: "300",
        icon: "manchurian",
      },
      {
        name: "Honey Chilli Potatoes",
        desc: "Crispy golden potato fries tossed in a sticky sweet and spicy sauce",
        price: "290",
        icon: "potato",
      },
      {
        name: "Tandoori Soya Chaap",
        desc: "High-protein soya pieces marinated in yogurt and aromatic herbs",
        price: "350",
        icon: "tikka-skewer",
      },
      {
        name: "Tandoori Bharwan Mushroom",
        desc: "Yogurt and Indian spice blended mushrooms cooked in a charcoal tandoor",
        price: "350",
        icon: "mushroom",
      },
      {
        name: "Tandoori Hara Phool",
        desc: "Broccoli with rich marination, char grilled",
        price: "350",
        icon: "broccoli",
      },
      {
        name: "Veg Seekh Kebab",
        desc: "Delicious Indian kebab of minced vegetables",
        price: "300",
        icon: "seekh-kabab",
      },
      { name: "Hara Bhara Kebab", price: "300", icon: "tikki" },
      { name: "Masala Peanut", price: "170", icon: "peanut" },
      { name: "Masala Papad", price: "140", icon: "papad" },
    ],
  },
  {
    id: "chinese-veg",
    title: "Chinese Veg Main Course",
    defaultTag: "veg",
    items: [
      {
        name: "Veg Noodles",
        desc: "Wok-tossed noodles and crisp vegetables seasoned with signature Asian sauces",
        price: "350",
        icon: "noodles",
      },
      {
        name: "Veg Hakka Noodles",
        desc: "Stir-fried noodles with crisp vegetables and savoury sauces",
        price: "340",
        icon: "noodles",
      },
      {
        name: "Pan Fried Veg Noodles",
        desc: "Boiled noodles pan fried until golden and crispy, tossed with stir-fried vegetables",
        price: "390",
        icon: "noodles",
      },
      {
        name: "Veg Chilli Garlic Noodles",
        desc: "Soft noodles tossed in a fiery aromatic sauce",
        price: "340",
        icon: "noodles",
      },
      {
        name: "Schezwan Noodles",
        desc: "Stir-fried noodles with vegetables in a bold, fiery red sauce",
        price: "380",
        icon: "noodles",
      },
      {
        name: "Veg Manchurian Gravy",
        desc: "Deep-fried mixed vegetable balls simmered in a rich, glossy, tangy sauce",
        price: "380",
        icon: "manchurian",
      },
      {
        name: "Chilli Paneer Gravy",
        desc: "Batter-fried paneer cubes tossed in a glossy spicy and tangy sauce",
        price: "400",
        icon: "paneer",
      },
      {
        name: "Mushroom Chilli Gravy",
        desc: "Crispy mushrooms and crunchy bell peppers in a rich, glossy sauce",
        price: "390",
        icon: "mushroom",
      },
      {
        name: "Soya Chilli Chaap Gravy",
        desc: "Golden-fried soya chaap tossed with crunchy bell peppers and onion",
        price: "350",
        icon: "tikka-skewer",
      },
      {
        name: "Maggie",
        desc: "The classic, beloved comfort noodles",
        price: "Plain ₹180 · Masala ₹240",
        icon: "noodles",
      },
    ],
  },
  {
    id: "chinese-nonveg",
    title: "Chinese Non-Veg Main Course",
    defaultTag: "nonveg",
    items: [
      {
        name: "Chicken Noodles",
        desc: "Noodles tossed with bite-sized chicken and crisp vegetables, soy sauce and aromatics",
        price: "450",
        icon: "noodles",
      },
      {
        name: "Chicken Hakka Noodles",
        desc: "Chicken wok-tossed with crunchy vegetables, soy sauce, ginger and garlic",
        price: "430",
        icon: "noodles",
      },
      {
        name: "Chicken Manchurian",
        desc: "Crispy deep-fried chicken tossed in a tangy, slightly sweet Manchurian sauce",
        price: "Half ₹400 · Full ₹650",
        icon: "manchurian",
      },
      {
        name: "Chilli Chicken Gravy",
        desc: "Crispy fried chicken in a bold, savoury, slightly tangy sauce with garlic and bell peppers",
        price: "Half ₹400 · Full ₹650",
        icon: "chilli",
      },
      {
        name: "Fish Chilli Gravy",
        desc: "Batter-fried fish in a vibrant indo-Chinese sauce with bell peppers, onion and green chillies",
        price: "Half ₹420 · Full ₹600",
        icon: "fish",
      },
      {
        name: "Chicken Schezwan Noodles",
        desc: "Tender chicken and crisp vegetables tossed in a bold, tangy schezwan sauce",
        price: "450",
        icon: "noodles",
      },
    ],
  },
  {
    id: "indian-veg",
    title: "Indian Veg Main Course",
    defaultTag: "veg",
    items: [
      {
        name: "Paneer Makhani",
        desc: "Soft paneer cubes simmered in a velvety, buttery tomato cream",
        price: "450",
        icon: "handi",
      },
      {
        name: "Paneer Kaali Mirch",
        desc: "Paneer in a creamy white gravy spiced with freshly crushed black pepper",
        price: "450",
        icon: "handi",
      },
      {
        name: "Malai Kofta",
        desc: "Paneer and potato dumplings in a velvety creamy tomato and onion curry",
        price: "500",
        icon: "manchurian",
      },
      {
        name: "Aloo Gobhi",
        desc: "Potatoes and cauliflower with spices and herbs",
        price: "350",
        icon: "gobhi",
      },
      {
        name: "Gobhi Adraki",
        desc: "Cauliflower florets stir-fried with julienned ginger, tomatoes and aromatic spices",
        price: "350",
        icon: "gobhi",
      },
      {
        name: "Jeera Aloo",
        desc: "Diced potatoes and cumin seeds sautéed with aromatic Indian spices",
        price: "300",
        icon: "potato",
      },
      {
        name: "Mili Juli Sabji",
        desc: "Seasonal vegetables and cottage cheese in a creamy aromatic onion-tomato gravy",
        price: "400",
        icon: "handi",
      },
      {
        name: "Muttar Mushroom",
        desc: "Mushroom and green peas in an onion-tomato gravy with spices and herbs",
        price: "400",
        icon: "mushroom",
      },
      {
        name: "Mushroom Do Pyaza",
        desc: "Button mushrooms in a spiced semi-dry onion and tomato gravy",
        price: "400",
        icon: "mushroom",
      },
      {
        name: "Aloo Capsicum",
        desc: "Potatoes and capsicum stir-fried with spices and herbs",
        price: "350",
        icon: "potato",
      },
      {
        name: "Aloo Matar",
        desc: "Potatoes and green peas simmered in a spiced onion-tomato gravy",
        price: "350",
        icon: "peas",
      },
      {
        name: "Pindi Channa",
        desc: "Slow-cooked chickpeas with aromatic spices, black tea and dry pomegranate seeds",
        price: "350",
        icon: "handi",
      },
      {
        name: "Corn Palak",
        desc: "Sweet corn kernels simmered in a silky, spiced spinach gravy",
        price: "420",
        icon: "corn",
      },
    ],
  },
  {
    id: "indian-nonveg",
    title: "Indian Non-Veg Main Course",
    defaultTag: "nonveg",
    items: [
      {
        name: "Butter Chicken",
        desc: "Boneless chicken simmered in a rich, creamy, mildly spiced tomato-butter gravy",
        price: "Half ₹500 · Full ₹800",
        icon: "curry",
      },
      {
        name: "Kadhai Chicken",
        desc: "Chicken tossed with bell peppers and onions in a thick, tangy tomato gravy",
        price: "Half ₹450 · Full ₹700",
        icon: "curry",
      },
      {
        name: "Chicken Curry",
        desc: "Bone-in chicken simmered in a rich sauce of onions, tomatoes, ginger, garlic and spices",
        price: "Half ₹450 · Full ₹750",
        icon: "curry",
      },
      {
        name: "Chicken Do Pyaza",
        desc: "Tender chicken simmered in a spiced onion and tomato gravy",
        price: "Half ₹430 · Full ₹750",
        icon: "curry",
      },
      {
        name: "Chicken Masala",
        desc: "Flavourful chicken with fresh spices, onion and tomato masala",
        price: "Half ₹430 · Full ₹750",
        icon: "curry",
      },
      {
        name: "Chicken Lababdar",
        desc: "Mughlai curry with succulent chicken in a mildly spiced tomato-onion gravy, cashews, cream and butter",
        price: "Half ₹450 · Full ₹780",
        icon: "curry",
      },
      {
        name: "Chicken Saagwala",
        desc: "Chicken cooked in a rich, silky spinach-based gravy",
        price: "Half ₹450 · Full ₹780",
        icon: "curry",
      },
      {
        name: "Chicken Tikka Masala",
        desc: "Char-grilled chicken simmered in a spiced velvety tomato and onion masala",
        price: "Half ₹450 · Full ₹790",
        icon: "curry",
      },
    ],
  },
  {
    id: "rice-biryani",
    title: "Rice & Biryani",
    defaultTag: "veg",
    items: [
      { name: "Steamed Rice", price: "220", icon: "rice" },
      { name: "Zeera Rice", price: "250", icon: "rice" },
      { name: "Peas Pulao", price: "280", icon: "rice" },
      { name: "Veg Pulao", price: "320", icon: "rice" },
      { name: "Curd Rice", price: "300", icon: "rice" },
      { name: "Lemon Rice", price: "280", icon: "rice" },
      { name: "Veg Biryani", price: "400", icon: "biryani" },
      { name: "Chicken Biryani", price: "550", icon: "biryani", tag: "nonveg" },
      { name: "Mutton Biryani", price: "650", icon: "biryani", tag: "nonveg" },
    ],
  },
  {
    id: "breads",
    title: "Breads",
    defaultTag: "veg",
    items: [
      { name: "Tandoori Roti", price: "60", icon: "roti" },
      { name: "Butter Roti", price: "70", icon: "roti" },
      { name: "Tawa Roti", price: "50", icon: "roti" },
      { name: "Plain Naan", price: "80", icon: "naan" },
      { name: "Butter Naan", price: "100", icon: "naan" },
      { name: "Garlic Naan", price: "120", icon: "naan" },
      { name: "Mix Kulcha", price: "150", icon: "naan" },
      { name: "Missi Roti", price: "80", icon: "roti" },
      { name: "Laccha Paratha", price: "80", icon: "paratha" },
    ],
  },
  {
    id: "dessert",
    title: "Dessert",
    defaultTag: "veg",
    items: [
      { name: "Hot Gulab Jamun", price: "160", icon: "gulab-jamun" },
      { name: "Fruit Cream", price: "150", icon: "dessert-cup" },
      { name: "Rice Pudding", price: "200", icon: "pudding" },
      { name: "Seviya Kheer", price: "200", icon: "pudding" },
      {
        name: "Choice of Ice Cream",
        desc: "Strawberry, chocolate, butterscotch or vanilla",
        price: "200",
        icon: "ice-cream",
      },
    ],
  },
];
