export type Room = {
  id: number;
  name: string;
  image: string;
  // Optional carousel images for the room card. Falls back to `image` if omitted.
  images?: string[];
  desc: string;
  inclusions: string[];
  seasonal: string;
  seasonalNote: string;
  offSeason: string;
  offSeasonNote: string;
  // Detail-page fields
  size: string;
  occupancy: string;
  bed: string;
  view: string;
  longDesc: string[];
  features: string[];
  gallery: string[];
};

export const roomsData: Room[] = [
  {
    id: 1,
    name: "Superior Rooms",
    image:
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/Videos%20and%20important%20images/IMG_9348_premium.jpg",
    images: [
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781447117181-9h68f4.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781447096623-ac99wd.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781447101049-5w8l0o.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781447091345-4nkm8u.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781448966768-qgjthb.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781448971449-mo1voj.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781448965533-t3mxks.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781449254667-h91055.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781449250487-xndw9z.jpg",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/superior-rooms/1781449256269-m0n8kq.jpg",
    ],
    desc: "Comfortable, well-appointed rooms with warm Pahari interiors and serene valley views.",
    inclusions: [],
    seasonal: "10,000",
    seasonalNote: "+ Applicable taxes",
    offSeason: "5,000",
    offSeasonNote: "+ applicable charges",
    size: "350 sq.ft",
    occupancy: "2 Adults",
    bed: "1 Queen Bed",
    view: "Garden & Valley View",
    longDesc: [
      "Our Superior Rooms offer a cosy and inviting retreat after a day in the mountains. Finished with warm local woodwork, handwoven textiles, and soft earthy tones, each room captures the understated charm of Pahari living.",
      "Large windows frame tranquil garden and valley views, while thoughtful modern comforts ensure your stay is as restful as it is authentic.",
    ],
    features: [
      "Free High-Speed Wi-Fi",
      "En-suite Bathroom",
      "Centrally Room Heating",
      "Smart TV",
      "Tea & Coffee Maker",
      "Daily Housekeeping",
    ],
    gallery: ["/room_dummy.png", "/about-section.png", "/hero-Background.png"],
  },
  {
    id: 2,
    name: "Honeymoon Suite",
    image:
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/Videos%20and%20important%20images/IMG%2011.png",
    images: [
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452370881-tmhgrk.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452369549-rel063.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452368219-c24gsq.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452366888-u1x5j8.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452365565-mq19ku.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452363999-7wq6mj.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452362860-p58in1.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452361731-ms6jft.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452360495-7qbesi.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452359289-czhx5q.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452358032-qpctk4.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452356899-w4cc9d.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452355853-t8yttr.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452354697-5xioih.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452353442-qbetmf.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452352021-lnlc4t.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/honeymoon-suite/1781452348952-xu5wml.png",
    ],
    desc: "A romantic retreat crafted for couples, complete with curated indulgences.",
    inclusions: ["Candlelight Dinner", "Cake", "Wine", "Flower Decorations"],
    seasonal: "15,000",
    seasonalNote: "+ Applicable taxes",
    offSeason: "8,000",
    offSeasonNote: "+ applicable charges",
    size: "450 sq.ft",
    occupancy: "2 Adults",
    bed: "1 King Bed",
    view: "Valley View",
    longDesc: [
      "The Honeymoon Suite is a celebration of romance, designed to make your special moments unforgettable. A spacious king bed, soft ambient lighting, and elegant decor set the scene for an intimate mountain getaway.",
      "Your stay comes complete with a candlelight dinner, a celebratory cake, a bottle of wine, and beautiful floral decorations, every detail arranged to delight.",
    ],
    features: [
      "Free High-Speed Wi-Fi",
      "Private Balcony",
      "Luxury En-suite Bathroom",
      "Centrally Room Heating",
      "Smart TV",
      "Premium Toiletries",
    ],
    gallery: ["/room_dummy.png", "/about-section.png", "/hero-Background.png"],
  },
  {
    id: 3,
    name: "The Opus Suite",
    image:
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/Videos%20and%20important%20images/IMG%2010%20(1).png",
    images: [
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453232313-dmwadv.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453231158-jaohyx.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453229896-sintoq.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453228703-xhcmn0.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453227412-sjfs3f.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453226186-m2hk4i.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453225029-3pjm3y.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453223841-iyf2d1.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453222657-3la12l.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453221405-v2zdg8.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453220104-9x9w7w.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453218893-lh217s.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453217781-837vzp.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453216570-pluahu.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453215340-0qaeio.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-opus-suite/1781453212529-mwtq7l.png",
    ],
    desc: "An indulgent suite featuring a private jacuzzi and refined mountain luxury.",
    inclusions: ["Private Jacuzzi"],
    seasonal: "20,000",
    seasonalNote: "+ Applicable taxes",
    offSeason: "13,000",
    offSeasonNote: "+ applicable charges",
    size: "550 sq.ft",
    occupancy: "2 Adults + 1 Child",
    bed: "1 King Bed",
    view: "Panoramic Mountain View",
    longDesc: [
      "The Opus Suite is where indulgence meets the mountains. Centered around a private jacuzzi, this generously sized suite invites you to unwind in complete comfort while taking in panoramic Himalayan vistas.",
      "Refined interiors, plush furnishings, and a dedicated lounge area make it the perfect choice for those seeking an elevated, restorative escape.",
    ],
    features: [
      "Private Jacuzzi",
      "Free High-Speed Wi-Fi",
      "Lounge Seating Area",
      "Luxury En-suite Bathroom",
      "Smart TV",
      "Centrally Room Heating",
    ],
    gallery: ["/room_dummy.png", "/about-section.png", "/hero-Background.png"],
  },
  {
    id: 4,
    name: "The Sanctuary Suite",
    image:
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/Videos%20and%20important%20images/IMG%2014%20(1).png",
    images: [
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453926259-d5hgyf.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453924649-j94ech.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453923457-x4u2dq.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453922224-kc9gjm.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453921055-m7ik53.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453919795-x7vfi6.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453917548-55ksqq.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453903912-lg14c2.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453901922-57safh.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453899683-muu8kf.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453897631-7ogpfx.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453895648-f25uc5.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453893008-zwgqec.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453882746-o8m9tj.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453881532-j41zmb.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453880394-cmfxp9.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453879216-j488ox.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453878045-yzze9q.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-sanctuary-suite/1781453875171-20mwcs.png",
    ],
    desc: "A tranquil haven of space and elegance, your private sanctuary in the hills.",
    inclusions: [],
    seasonal: "20,000",
    seasonalNote: "+ Applicable taxes",
    offSeason: "13,000",
    offSeasonNote: "+ applicable charges",
    size: "550 sq.ft",
    occupancy: "2 Adults + 1 Child",
    bed: "1 King Bed",
    view: "Forest & Mountain View",
    longDesc: [
      "The Sanctuary Suite lives up to its name, a serene, spacious haven designed for deep rest and quiet reflection. Surrounded by forest and mountain views, it offers a calming escape from the rush of everyday life.",
      "Elegant interiors, a comfortable seating area, and an abundance of natural light create a peaceful atmosphere you'll never want to leave.",
    ],
    features: [
      "Free High-Speed Wi-Fi",
      "Private Balcony",
      "Lounge Seating Area",
      "Luxury En-suite Bathroom",
      "Smart TV",
      "Centrally Room Heating",
    ],
    gallery: ["/room_dummy.png", "/about-section.png", "/hero-Background.png"],
  },
  {
    id: 5,
    name: "The Himalayan Chester Suite",
    image:
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/Videos%20and%20important%20images/IMG%2020.png",
    images: [
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454406985-kzriug.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454404453-al9198.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454401733-9j50io.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454399476-tks53l.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454397472-545qey.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454395180-l2ajcf.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454392486-oh51ve.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454389583-ll2l7p.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454386811-d1ifva.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454383866-hskm4q.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454381357-zbs8n5.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454380127-gia3wr.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454379019-qknd1l.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454377657-vzpwno.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454376526-7jtzl6.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454375293-48k3yy.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454373979-45sd3r.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454372932-vhl65t.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454371786-0o8c2y.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454370191-1ix5da.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454368644-99nwio.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454366721-84ob6u.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454365439-k4kosq.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454364315-byri9m.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454363116-k3yfn7.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454361850-to2epw.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454360672-a4i8e7.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454359384-vm2jqt.png",
      "https://ksfgavzcnkfckvsuxfxk.supabase.co/storage/v1/object/public/gallery/the-himalayan-chester-suite/1781454356538-9mq0q7.png",
    ],
    desc: "Our signature suite, the pinnacle of heritage luxury and panoramic Himalayan grandeur.",
    inclusions: [],
    seasonal: "30,000",
    seasonalNote: "+ Applicable taxes",
    offSeason: "20,000",
    offSeasonNote: "+ applicable charges",
    size: "750 sq.ft",
    occupancy: "3 Adults",
    bed: "1 King Bed + Living Area",
    view: "360° Himalayan View",
    longDesc: [
      "The Himalayan Chester Suite is our crowning accommodation, an expansive sanctuary that embodies the very best of heritage luxury. A separate living area, premium furnishings, and sweeping 360° views of the Himalayas make every moment feel extraordinary.",
      "Crafted for guests who expect nothing less than perfection, this signature suite blends timeless Pahari craftsmanship with the finest modern comforts.",
    ],
    features: [
      "Free High-Speed Wi-Fi",
      "Separate Living Area",
      "Private Balcony",
      "Luxury En-suite Bathroom",
      "Smart TV",
      "Premium Toiletries",
    ],
    gallery: ["/room_dummy.png", "/about-section.png", "/hero-Background.png"],
  },
];

export function getRoomById(id: number): Room | undefined {
  return roomsData.find((room) => room.id === id);
}
